package uz.javokhir.qr.master.ui.localization

object AppStrings {
    const val text = "Text"
    const val wifi = "Wi-Fi"
    const val calendarEvent = "Calendar event"
    const val bizCard = "Biz card"
    const val contactVCard = "Contact - vCard"
    const val businessVCard = "Business - vCard"
    const val phoneNumber = "Phone number"
    const val sms = "SMS"
    const val emailAddress = "Email address"
    const val youtube = "YouTube"
    const val whatsApp = "WhatsApp"
    const val instagram = "Instagram"
    const val facebook = "Facebook"
    const val twitter = "Twitter"
    const val tiktok = "TikTok"
    const val telegram = "Telegram"
    const val vkontakte = "ВКонтакте"
    const val twitch = "Twitch"
    const val linkedin = "LinkedIn"
    const val github = "Github"
    const val medium = "Medium"
    const val dribbble = "Dribbble"
    const val behance = "Behance"
    const val copiedText = "Copied Text"
    const val copiedToClipboard = "Copied to clipboard"
    const val photoSaved = "Photo saved successfully"
    const val cancel = "Cancel"
    const val actionContinue = "Continue"
    const val create = "Create"
    const val delete = "Delete"
    const val next = "Next"
    const val ok = "OK"
    const val preview = "Preview"
    const val save = "Save"
    const val scan = "Scan"
    const val select = "Select"
    const val selectLocation = "Select location"
    const val share = "Share"
    const val skip = "Skip"
    const val start = "Start"
    const val addContent = "Add content"
    const val addLogo = "Add logo"
    const val address = "Address"
    const val alignQrCode = "Align QR Code / Bardcode within frame to scan"
    const val allDayEvent = "All day event"
    const val backgroundColor = "Background Color"
    const val chromeCustomTabs = "Chrome Custom Tabs"
    const val clickCreateButton = "Click create button to start create QR Code."
    const val clickScanButton = "Click scan button to start scan QR Code."
    const val color = "Color"
    const val communication = "Communication"
    const val companyName = "Company name"
    const val cornerStyle = "Corner style"
    const val created = "Created"
    const val creator = "Creator"
    const val customize = "Customize"
    const val customizeQr = "Customize QR"
    const val dark = "Dark"
    const val description = "Description"
    const val dotColor = "Dot color"
    const val dotsColor = "Dots color"
    const val dotsStyle = "Dots style"
    const val egPlaceholderAddress = "e.g. New York City Spring Avenue 9/18"
    const val egPlaceholderCompanyName = "e.g. My Company"
    const val egPlaceholderDate = "e.g. 12 Dec 2024"
    const val egPlaceholderDateTime = "e.g. 12 Dec 2024 10:40"
    const val egPlaceholderEmail = "e.g. name@email.com"
    const val egPlaceholderEventDescription =
        "e.g. Celebrate the queen of our hearts! Join us in honoring our beloved mother on her special day."
    const val egPlaceholderEventName = "e.g. Birthday mother"
    const val egPlaceholderFirstName = "e.g. Paul"
    const val egPlaceholderIndustry = "e.g. Animation Studio"
    const val egPlaceholderJob = "e.g. Android Developer"
    const val egPlaceholderLastName = "e.g. Jones"
    const val egPlaceholderLatitude = "e.g. 24.467035"
    const val egPlaceholderLocation = "e.g. Rooftop Restaurant - Skyline Bistro"
    const val egPlaceholderLongitude = "e.g. 39.610947"
    const val egPlaceholderPhone = "e.g. +1809999999"
    const val egPlaceholderSmsMessage = "e.g. Running late. Be there in 10 mins."
    const val egPlaceholderSubject = "e.g. QR Master app"
    const val egPlaceholderText = "e.g. Discover the ancient Silk Road in Uzbekistan."
    const val egPlaceholderWebsite = "e.g. www.yourwebsite.com"
    const val egPlaceholderWifiName = "e.g. My Wi-Fi"
    const val egPlaceholderWifiPassword = "e.g. 11111111"
    const val endDate = "End date"
    const val endDateTime = "End date and time"
    const val enterValue = "Enter value"
    const val eventName = "Event name"
    const val name = "Name"
    const val frameColor = "Frame color"
    const val frameStyle = "Frame style"
    const val general = "General"
    const val hidden = "Hidden"
    const val history = "History"
    const val industry = "Industry"
    const val job = "Job"
    const val lastName = "Last name"
    const val latitude = "Latitude"
    const val library = "Library"
    const val light = "Light"
    const val location = "Location"
    const val longitude = "Longitude"
    const val message = "Message"
    const val networkName = "Network name"
    const val noContentFound = "No content found!"
    const val onboardingDescription1 = "Edit and change your QR codes anytime."
    const val onboardingDescription2 = "Track your QR codes and get insights about scans."
    const val onboardingDescription3 = "Create and edit many QR codes in no time."
    const val onboardingDescription4 = "Create transparent QR codes and reusable design templates."
    const val onboardingTitle1 = "Dynamic QR Codes"
    const val onboardingTitle2 = "Scan Statistics"
    const val onboardingTitle3 = "Bulk Creation and Editing"
    const val onboardingTitle4 = "More Design Options"
    const val openWebPages = "Open web pages automatically"
    const val other = "Other"
    const val others = "Others"
    const val password = "Password"
    const val qrCode = "QR Code"
    const val qrCodePattern = "QR code pattern"
    const val rateUs = "Rate us"
    const val scanControls = "Scan controls"
    const val scanned = "Scanned"
    const val scanner = "Scanner"
    const val searchQrCode = "Search QR Code"
    const val selectDate = "Select date"
    const val selectDateAndTime = "Select Date and Time"
    const val selectTime = "Select time"
    const val settings = "Settings"
    const val socialMedia = "Social Media"
    const val startDate = "Start date"
    const val startDateTime = "Start date and time"
    const val subject = "Subject"
    const val systemDefault = "System default"
    const val tellFriends = "Tell friends"
    const val theme = "Theme"
    const val vibrate = "Vibrate"
    const val web = "Web"
    const val website = "Website"
    const val whatsappNumber = "WhatsApp number"
    const val searchOnWeb = "Search on the web"
    const val openWebsite = "Open website"
    const val sendSms = "Send SMS"
    const val sendEmail = "Send email"
    const val addContact = "Add contact"
    const val showLocation = "Show location"
    const val shareDescription = "QR Master - Your all-in-one QR scanner and creator app for quick and effortless code scanning creation and customization. Unlock a world of information with a simple scan and easily generate personalized codes. Get QR Master now!"
    const val connectToWifi = "Connect to Wi-Fi"
    const val copyNetworkName = "Copy network name"
    const val copyPassword = "Copy password"
    const val copy = "Copy"
    const val edit = "Edit"
    const val viewAddress = "View address"
    const val addToCalendar = "Add to calendar"
    const val scanImage = "Scan image"
    const val dragMarkers = "Drag the white markers till the barcode is detected"

    private const val mChannelName = "channel name"
    private const val mProfile = "profile"
    private const val mUsername = "username"
    private const val mDial = "Dial"

    fun socialMediaChannel(channel: String): String {
        return "$channel $mChannelName"
    }

    fun socialMediaProfile(profile: String): String {
        return "$profile $mProfile"
    }

    fun socialMediaUsername(username: String): String {
        return "$username $mUsername"
    }

    fun dial(phone: String): String {
        return "$mDial $phone"
    }
}